version: '2'

services:
  
  wordpress:
    image: wordpress
    links:
     - mysql
    ports:
     - "50000:80"
    working_dir: /var/www/html
    volumes:
     - ./dev/wordpress:/var/www/html
     - ./imaginedsf-custom-theme:/var/www/html/wp-content/themes/imaginedsf-custom-theme

  mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./dev/mysql:/var/lib/mysql
     - ./dev/dumps:/dumps
